# Generated by Django 4.0.3 on 2022-04-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tododetails',
            old_name='user_id',
            new_name='user',
        ),
    ]
